spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: ture
    properties:
      hibernate: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    password:
    url: jdbc:h2:mem:price_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2